=== shreyathacker21/Recipe/HomePage.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Home page contain one or more recipe -->
<!ELEMENT Recipe_Home (RecipeID+) >

<!-- each recipe has one or more image and one or more webpage -->
<!ELEMENT RecipeID (Image+,Web+) >
<!ATTLIST RecipeID ID CDATA #REQUIRED >

<!ELEMENT Web (#PCDATA) >
<!ATTLIST Web href CDATA #REQUIRED>

<!ELEMENT Image ANY >
<!ATTLIST Image pic CDATA #REQUIRED >

=== shreyathacker21/Recipe/HomePage.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="homepage.xsl"?>
<!DOCTYPE Recipe_Home SYSTEM "HomePage.dtd">
<Recipe_Home>
    
       <RecipeID ID="1"> 
           <Image pic="banana-bread-600.jpg">
               
           </Image>
           <Web href="Recipe2_BananaBread.xml">
           Banana Bread
       </Web>
           
       </RecipeID>
    
    <RecipeID ID="2"> 
        <Image pic="calamari.jpg">
            
        </Image>
        <Web href="Calamari_group4.xml">
            Calamari
        </Web>
        
    </RecipeID>
    
    <RecipeID ID="3"> 
        <Image pic="Recipe3.jpg">
            
        </Image>
        <Web href="ChickenChimichangas.xml">
            Chicken Chimichangas
        </Web>
        
    </RecipeID>
    
</Recipe_Home>
